kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |-
    <system>
      log_level debug
    </system>
   
    <source>
      @type http
      port 9880
      bind 0.0.0.0
      body_size_limit 32m
      keepalive_timeout 10s
    </source>

    <source>
      @type forward
      port 24224
      bind 0.0.0.0
      tag kube.forward
    </source>

    <match **>
      @type stdout
    </match>