kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |-
    <system>
      log_level warn
    </system>
   
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
      tag kube.forward
    </source>

    <match **>
      @type elasticsearch
      @id out_es
      @log_level info
      include_tag_key true
      host elasticsearch
      port 9200
      scheme http
      logstash_format true
      logstash_prefix logstash
      index_name logstash
      type_name fluentd
      reload_connections false
      reconnect_on_error true
      reload_on_failure true
      log_es_400_reason false
      <buffer>
        flush_thread_count 8
        chunk_limit_size 2M
        queue_limit_length 32
        retry_max_interval 30
        flush_interval 5s
        retry_forever false
      </buffer>
    </match>
