apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: logging
  labels:
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: zhulinwei/logging:latest
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 20Mi
        ports:
        - containerPort: 24224
      terminationGracePeriodSeconds: 30