apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: logging
  labels:
    app: example
spec:
  ports:
  - port: 24224
    protocol: TCP
  selector:
    app: example
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: logging
  labels:
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: logging:latest
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 24224
      terminationGracePeriodSeconds: 30